<?php
 $username="root";
 $server="localhost";
 $password="";
 $database="sample";
 $conn=mysqli_connect($server,$username,$password,$database);
 if(!$conn)
 {
   die("fuck".mysqli_connect_error());
 }
  ?>
